#!/bin/bash

# Switch package.json to the version for Cypress or Playwright

# at_switchto <tool>
# tool = playwright OR cypress

SOURCE_FILE="package.json"
PLAYWRIGHT_FILE="playwrite.package.json"
CYPRESS_FILE="cypress.package.json"

if [ -z "$1" ]
  then
  echo "Please provide target framework (playwright OR cypress)."
  exit
fi

if [ "$1" == "cypress" ]; then
  echo "Copying package.json to $PLAYWRIGHT_FILE"
  cp $SOURCE_FILE $PLAYWRIGHT_FILE
  echo "Using $CYPRESS_FILE."
  cp $CYPRESS_FILE $SOURCE_FILE
else
  echo "Copying package.json to $CYPRESS_FILE"
  cp $SOURCE_FILE $CYPRESS_FILE
  echo "Using $PLAYWRIGHT_FILE."
  cp $PLAYWRIGHT_FILE $SOURCE_FILE
fi 